name: project-name
channels:
- conda-forge
dependencies:
- python=3.11
- jupyter
- jupyterlab
- conda
- mamba
- ipython
- ipykernel
- irkernel
- numpy
- matplotlib
- scipy
- pre-commit
- black
- nbstripout
- mypy
- ruff
- flake8
- pycodestyle
- pydocstyle
- pytest
- pytest-cov
- pytest-xdist
- pip:
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - mknotebooks
  - Sphinx

